apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: g3ccr33wk-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:9582ffe2c5d83a4ddcbf41ef5ac14478e96158ac@sha256:4a0d3e3af45c35ffe78622b980ebaab76ec4d7fa13571ad26625f1e3255b551f
          name: container-image
